### ISSUE TITLE
Problem with removing and make owner private chat members 

### ISSUE THREAD

**Issue by ArtCrafter2999** [SparkChats/API#152]
Request URL: https://localhost:7060/api/private-chats/654e9183af149d7e0400dedf/kick
Request Method: DELETE
Status Code: 404 Not Found
Remote Address: [::1]:7060
Referrer Policy: strict-origin-when-cross-origin

```json
{
    "title": "Entity UserProfile (7aef2538-e1b3-42d7-a3db-a2809a81ac91) not found",
    "status": 404
}
```

```
Entity UserProfile (7aef2538-e1b3-42d7-a3db-a2809a81ac91) not found
      Sparkle.Application.Common.Exceptions.EntityNotFoundException: Entity UserProfile (7aef2538-e1b3-42d7-a3db-a2809a81ac91) not found
         at Sparkle.DataAccess.BaseSqlRepository`2.FindAsync(TKey id, CancellationToken cancellationToken) in D:\DiscordClone\DataAccess\BaseSqlRepository.cs:line 37
         at Sparkle.Application.Chats.GroupChats.Commands.RemoveUserFromGroupChat.RemoveUserFromGroupChatCommandHandler.Handle(RemoveUserFromGroupChatCommand command, CancellationToken cancellationToken) in D:\DiscordClone\Applicati
on\Chats\GroupChats\Commands\RemoveUserFromGroupChat\RemoveUserFromGroupChatCommandHandler.cs:line 26
         at Sparkle.Application.Common.Behaviors.LoggingBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in D:\DiscordClone\Application\Common\Behaviors\LoggingBehavior.cs:line
33
         at Sparkle.Application.Common.Behaviors.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in D:\DiscordClone\Application\Common\Behaviors\ValidationBehavior.cs
:line 27
         at Sparkle.WebApi.Controllers.PrivateChatsController.RemoveGroupChatMember(String chatId, RemoveUserFromGroupChatRequest request) in D:\DiscordClone\WebApi\Controllers\PrivateChatsContoller.cs:line 292
         at lambda_method934(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] argu
ments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

```

**Comment by Grabtot** [comment]
это был баг на фроне
